cache:
  yarn: true
  directories:
    - $HOME/cache
    - $HOME/.m2
services:
  - mysql
  - postgresql
  - mongodb
matrix:
  include:
    - env: OPENRASP_LANG=php7 CC=gcc-4.9 CXX=g++-4.9 NO_INTERACTION=1 REPORT_EXIT_STATUS=1
      language: php
      php: 7.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - openssl
            - libssl-dev
            - libsslcommon2-dev
            - libcurl4-openssl-dev
            - libpcre3-dev
            - apache2
            - gdb
before_script:
  - bash ./travis/$OPENRASP_LANG/before_script.sh
script:
  - travis_retry bash ./travis/$OPENRASP_LANG/script.sh
after_failure:
  - cat /tmp/openrasp/logs/crash/*
  - for i in $(find /tmp/coredump/ -maxdepth 1 -name 'core*' -print); do gdb php /tmp/coredump/core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
